spring:
  application:
    name: usuarios
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate.ddl-auto: "update"
  datasource:
    username: "root"
    password: "root"
    url: "jdbc:mysql://10.170.129.231:3306/usuarios?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"