spring:
  application:
    name: usuarios
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
  datasource:
    username: "root"
    password: "root"
    url: "jdbc:mysql://35.192.136.197:3306/usuarios?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"