spring:
  application:
    name: usuarios
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    username: "root"
    password: "root"
    url: "jdbc:mysql://35.192.136.197:3306/usuarios?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"